"""user account confirmation and password set fields

Revision ID: 2346bc15629f
Revises: f6aa28fef43f
Create Date: 2023-07-27 05:16:26.654600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2346bc15629f'
down_revision = 'f6aa28fef43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pw_last_set', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_email_verified')
        batch_op.drop_column('pw_last_set')

    # ### end Alembic commands ###
